### ISSUE TITLE
Restyle Checkbox component

### ISSUE THREAD

**Issue by jacten** [coding-circle/charades#81]
Checkbox just uses native styles. 

We should restyle this to match other designs. See @anderspollack for checkbox designs. I believe they exist on the figma.

**Comment by jacten** [comment]
![image](https://user-images.githubusercontent.com/34265184/103233125-19acb800-48f1-11eb-91fd-4bcb712e4c62.png)

I assigned this to you @chedgo. Can do it after your other task. Google will be your friend as restyling native checkboxes is a bit interesting! I can send you the figma too so you can see the designs.

I think it's probably easier to jump on a call to fully explain.

**Comment by chedgo** [comment]
I'm all in around 1 my time
